cloud:
  aws:
    key:
      access: ""
      secret: ""
    region: ""
    s3:
      bucket:
        limit:
          size: "10"

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB